### ISSUE TITLE
Anteproyecto: Codigo del proyecto

### ISSUE THREAD

**Issue by harpomaxx** [sofiabarbeito/ia-uncuyo-2021#1]
Solo es necesario  un UNICO codigo de proyecto.

Por ejemplo para un Título del proyecto:  "Algoritmo genético  problemas de tráfico vehicular”

Código del proyecto:  “GATRAF”

**Comment by harpomaxx** [comment]
Todavia no se adapta al tipo de codigo. Un ejemplo para el caso de uds seria LSTASK (Local Shearch TASK). 
No se olviden de cerrar los issues una vez terminados junto a algun comentario.

**Comment by sofiabarbeito** [comment]
Cambiamos el código del proyecto por su sugerencia: LSTASK
