### ISSUE TITLE
Anteproyecto: Falta copia en el repo del otro integrante

### ISSUE THREAD

**Issue by harpomaxx** [sofiabarbeito/ia-uncuyo-2021#2]
Lucia deberia tener una copia igual de esta carpeta con toda la info del anteproyecto

**Comment by sofiabarbeito** [comment]
Lucía ahora tiene una copia igual en su repo [https://github.com/LuciaCairo/ia-uncuyo-2021-/blob/main/proyecto_final/anteproyecto.md](url)

**Comment by sofiabarbeito** [comment]
Lucía ya tiene una copia igual en su repo: https://github.com/LuciaCairo/ia-uncuyo-2021-/blob/main/proyecto_final/anteproyecto.md
